footprint: [[-0.35,-0.25], [-0.35,0.25], [0.35,0.25], [0.35,-0.25]]
robot_base_frame: base_link

lethal_cost_threshold: 100

unknown_cost_value: 255


obstacle_layer:
   observation_sources: scan
   scan: 

      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      expected_update_rate: 0.20
   obstacle_range: 2.5
   raytrace_range: 3.0
   enabled: true

inflation_layer:
   inflation_radius: 0.3
   enabled: true

footprint_layer:
   enabled: true

sonar_layer:
   enabled: true