global_frame: /odom
update_frequency: 5.0
publish_frequency: 2.0
resolution: 0.10
static_map: true
rolling_window: false
track_unknown_space: true
unknown_cost_value: 255

plugins:
   - name: static_map
     type: "costmap_2d::StaticLayer"
   - name: obstacle_layer
     type: "costmap_2d::ObstacleLayer"
   - name: footprint_layer
     type: "costmap_2d::FootprintLayer"
   - name: inflation_layer
     type: "costmap_2d::InflationLayer"